# docker-compose.infra.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ocr-postgres
    environment:
      POSTGRES_USER: ocr_cuong
      POSTGRES_PASSWORD: ocr_cuong
      POSTGRES_DB: ocr_cuong_db
    ports:
      - "5432:5432"
    volumes:
      - ocr_postgres_data:/var/lib/postgresql/data
    networks:
      - ocr-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ocr-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ocr-network
    restart: always

  redis:
    image: redis:alpine
    container_name: ocr-redis
    command: redis-server --requirepass infini_rag_flow
    ports:
      - "6379:6379"
    networks:
      - ocr-network
    restart: always

  minio:
    image: minio/minio
    container_name: ocr-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: rag_flow
      MINIO_ROOT_PASSWORD: infini_rag_flow
    volumes:
      - ocr_minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - ocr-network
    restart: always

networks:
  ocr-network:
    name: ocr-network
    driver: bridge

volumes:
  ocr_postgres_data:
  ocr_minio_data: